Python_practice_develop
Azinuss/Homework2 pull request #1
Opened 2023-03-19 16:55 UTC by Azinuss

Сделаны все задания

2023-03-25 10:01 UTC, vladefr97 requested changes

2023-03-25 10:01 UTC, vladefr97 commented on Задача 1/main.py
> +            print('Эта строка  не полином')
Лушче возвращать True или False в функции и в зависимости от результа делать print

2023-03-25 10:01 UTC, vladefr97 commented on Задача 1/main.py
> +def polindrome(str):
Стараемся использовать типизацию в проекте

2023-03-25 10:01 UTC, vladefr97 commented on Задача 1/main.py
> +        if (str[i] != str[-i-1]):
Скобки здесь можно убрать

2023-03-25 10:01 UTC, vladefr97 commented on Задача 2/main2.py
> +    return print(list(filter(fn,mass)))
Тут возвращаешь None. Надо убрать  print и возвращать list

2023-03-25 10:01 UTC, vladefr97 commented on Задача 3/main3.py
> +class figure ():
Классы принято называть в CamelCase   и с большой буквы (см. нотацию pep8)

2023-03-25 10:01 UTC, vladefr97 commented on Задача 3/main3.py
> +    def AreaCompare (self, other):
Методы и функции принято называть в snake_case   и с маленькой буквы (см. нотацию pep8)

2023-03-25 10:01 UTC, vladefr97 commented on Задача 3/main3.py
> +            if (self.area > other.area): return print('Первая фигура больше второй по площади')
Надо возвращать логический результат сравнения, а не делать return print

2023-03-25 10:01 UTC, vladefr97 commented on Задача 4/main4.py
> +        if(self.avrrating == 5): self.paymant = 6000
payment пишется

2023-03-25 10:01 UTC, vladefr97 commented on Задача 4/main4.py
> +        if(self.avrrating == 5): self.paymant = 6000
Из констуктора желательно по максимуму выносить логику

2023-03-25 10:01 UTC, vladefr97 commented on Задача 4/main4.py
> +        if(self.avrrating == 5): self.paymant = 6000
Стараемся не использовать литералы в коде. Все значения (размер стипендии, значение оценки) нужно вынести в константы

2023-03-26 16:53 UTC, Azinuss commented on Задача 4/main4.py
> +        if(self.avrrating == 5): self.paymant = 6000
А куда ее вынести? Или вынести это в отдельную функцию которая будет вызыватся в кострукторе?

2023-06-07 15:21 UTC, vladefr97 approved these changes

2023-06-07 15:21 UTC, vladefr97 commented on Задача 3/main3.py
> +        self.area = 3.14 * self.r ** 2
Лучше использовать math.pi

2023-06-07 15:24 UTC, merged